---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-app-config
  labels:
    app: {{ .Release.Name }}
data:
  DATABASE_URL: {{ .Values.database_url }}
  RACK_ENV: {{ .Values.environment }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
spec:
  replicas: {{ .Values.app.replica_count }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.app.image }}
        command: ["sh", "-c", "{{ .Values.app.command }}"]
        ports:
        - containerPort: {{ .Values.app.port }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-app-config
        resources:
{{ toYaml .Values.app.resources | indent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}-app
  ports:
    - name: app
      protocol: TCP
      port: 80
      targetPort: {{ .Values.app.port }}
