environment: 'production'
database_url: 'postgresql://postgres:postgres@postgres/dev'

app:
  replica_count: 1
  port: 3000
  command: "bundle exec rackup --port 3000 --host 0.0.0.0"
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

migrate:
  command: "bundle exec rake db:create db:migrate db:seed"
