name: cleanup
on:
  schedule:
    - cron:  '0 19 * * *'
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ops/infrastructure/live
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.2

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve

      - name: Clean Remaining Load Balancers
        run: aws elb describe-load-balancers | jq '.LoadBalancerDescriptions | .[] | .LoadBalancerName' | xargs -L1 aws elb delete-load-balancer --load-balancer-name
